# Action Workflow to implement CI/CD to my website

name: Lint, Test, Build, and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build:ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # Or use OIDC configuration
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS S3
        run: aws s3 sync dist/Website-JohnBucher/browser s3://your-s3-bucket-name --delete # Sync current directory to S3
        env:
          AWS_REGION: us-east-1
        
      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/Website-JohnBucher/browser # The folder the action should deploy.
